#ifndef CONFIG_H
#define CONFIG_H

#define SCREEN_HEIGHT 128
#define SCREEN_WIDTH 128
#define SCREEN_SIZE (SCREEN_WIDTH * SCREEN_HEIGHT)

#define CHR_WIDTH 8
#define CHR_HEIGHT 8

#define CHR_SCALE 1

#define WINDOW_WIDTH (CHR_WIDTH * SCREEN_WIDTH)
#define WINDOW_HEIGHT (CHR_HEIGHT * SCREEN_HEIGHT)

#define TARGET_WINDOW_WIDTH (WINDOW_WIDTH * CHR_SCALE)
#define TARGET_WINDOW_HEIGHT (WINDOW_HEIGHT * CHR_SCALE)
#define WINDOW_TITLE "WorldGen"

#endif //  CONFIG_H
