#include "tile.h"
#include "display.h"
#include "palette.h"
#include <stdbool.h>


Glyph tile_glyphs[] = {

[TILE_AIR] = glyph(0x00, PAL_BLACK, PAL_BLACK),
[TILE_BEDROCK] = glyph(0xB0, PAL_GRAY(0x20), PAL_BLACK),

[TILE_STONE] = glyph(0xDB, PAL_STONE, PAL_BLACK),
[TILE_DIRT] = glyph(0xB1, PAL_BROWN, PAL_DARK_BROWN),
[TILE_MOSS] = glyph('#', PAL_GREEN, PAL_STONE),


[TILE_CRYSTAL] = glyph(0xCE, PAL_PURPLE, PAL_BLACK),
[TILE_EMERALD] = glyph(0x09, PAL_GREEN, PAL_PURPLE),
[TILE_AMETHYST] = glyph(0x09, PAL_BLUE, PAL_PURPLE),
[TILE_RUBY] = glyph(0x09, PAL_RED, PAL_PURPLE),

[TILE_FUNGAL] = glyph(0xB0, PAL_FUNGUS_2, PAL_FUNGUS),
[TILE_FUNGAL_MOSS] = glyph('#', PAL_GREEN, PAL_FUNGUS),

[TILE_ICE] = glyph(0x0F, PAL_BLUE, RGB(0x5, 0x10, 0xB2)),
[TILE_SNOW] = glyph(0xB0, PAL_BLUE, PAL_WHITE),

[TILE_MAGMA] = glyph(0xF7, PAL_RED, RGB(0x55, 0, 0)),
[TILE_HELLSTONE] = glyph(0x9D, PAL_RED, PAL_DARK_BROWN),

[TILE_VOID] = glyph(0xED, PAL_GRAY(0x33), PAL_BLACK),
[TILE_VOIDSTONE] = glyph(0x08, PAL_STONE, PAL_BLACK),

[TILE_STEAM] = glyph(0xB0, PAL_GRAY(0x40), PAL_BLACK),
[TILE_CHARCOAL] = glyph(0xB0, PAL_BLACK, PAL_GRAY(0x30)),

[TILE_GRASS] = glyph(0xB1, PAL_GREEN, PAL_DARK_BROWN),
[TILE_COAL] = glyph(0x0F, PAL_BLACK, PAL_STONE),
[TILE_IRON] = glyph(0x9C, PAL_RED, PAL_STONE),
[TILE_DIAMOND] = glyph(0x0F, PAL_BLUE, PAL_STONE),

};
